# TODO(rz): Try: docker setup instead: https://circleci.com/docs/2.0/language-java/
# TODO(rz): Try:
# CircleCI config schema is versioned.
version: 2.1

# orbs are config packages to include.
orbs:
  gradle: circleci/gradle@1.0.11
  slack: circleci/slack@3.3.0

workflows:
  build_and_test:
    jobs:
      - build

jobs:
  build:
    machine: true
    parallelism: 4
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Open permissions on cache dir
          command: sudo chmod -R a+rwx /root
      - run:
          name: Generate Cache Checksum
          command: find . -name 'build.gradle' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          keys:
            - gradle-{{ checksum "/tmp/gradle_cache_seed" }}
            - gradle-
      # - run:
      #     name: Install
      #     command: |
      #       GRADLE="./gradlew --no-daemon --max-workers=2"
      #       export GRADLE_OPTS="-Xmx4g -Xms4g"

      #       if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
      #         echo -e "Assemble Pull Request #$CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
      #         $GRADLE assemble
      #       else
      #         echo -e 'WARN: Only building on CircleCI'
      #         $GRADLE assemble
      #       fi

      - run:
          name: Build
          command: |
            GRADLE="./gradlew --no-daemon --max-workers=2"
            #export GRADLE_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
            export GRADLE_OPTS="-Xmx4g -Xms4g"

            # Get list of classnames of tests that should run on this node
            CLASSNAMES=$(circleci tests glob "**/src/test/**/*.{kt,java,groovy}" \
              | circleci tests split --show-counts=true --total=4 --split-by=timings --timings-type=classname)

            # Format the arguments to "./gradlew test"
            # GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared filter for Gradle: $CLASSNAMES"

            if [ "x$CIRCLE_PULL_REQUEST" != "x" ]; then
              echo -e "Build Pull Request $CIRCLE_PULL_REQUEST => Branch [$CIRCLE_BRANCH]"
              ./gradlew test -i PtestFilter="$CLASSNAMES" $GRADLE_ARGS
            else
              echo -e 'WARN: Only building on CircleCI'
              ./gradlew test -i PtestFilter="$CLASSNAMES" $GRADLE_ARGS
            fi
      - save_cache:
          when: always
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/gradle_cache_seed" }}
      #- slack/notify


